const num = (v) => {
  if (v === '' || v == null) return undefined;
  const n = Number(v);
  return Number.isFinite(n) ? n : undefined;
};

const str = (v) => (v == null || v === '' ? undefined : String(v).trim());

/** Portal route → bulk CSV import config */
export const BULK_IMPORT_BY_ROUTE = {
  '/portal/loads': {
    entity: 'Load',
    label: 'Loads',
    headers: ['load_number', 'origin_city', 'origin_state', 'destination_city', 'destination_state', 'status', 'rate', 'miles', 'commodity', 'pickup_date', 'delivery_date'],
    required: ['load_number', 'origin_city', 'destination_city'],
    columnHint: 'load_number, origin/destination, status, rate, miles, commodity, dates',
    exampleRows: [{
      load_number: 'LD-90001',
      origin_city: 'Dallas',
      origin_state: 'TX',
      destination_city: 'Atlanta',
      destination_state: 'GA',
      status: 'booked',
      rate: '2850',
      miles: '780',
      commodity: 'General Freight',
      pickup_date: '2026-07-10',
      delivery_date: '2026-07-12',
    }],
    mapRow: (row) => ({
      load_number: str(row.load_number),
      origin_city: str(row.origin_city),
      origin_state: str(row.origin_state),
      destination_city: str(row.destination_city),
      destination_state: str(row.destination_state),
      status: str(row.status) || 'booked',
      rate: num(row.rate),
      miles: num(row.miles),
      commodity: str(row.commodity),
      pickup_date: str(row.pickup_date),
      delivery_date: str(row.delivery_date),
    }),
    preview: (row) => `${row.load_number} · ${row.origin_city || '?'} → ${row.destination_city || '?'}`,
  },
  '/portal/fleet': {
    entity: 'Vehicle',
    label: 'Fleet Units',
    headers: ['unit_number', 'unit_type', 'make', 'model', 'year', 'vin', 'license_plate', 'status', 'odometer', 'trailer_type', 'trailer_length'],
    required: ['unit_number'],
    columnHint: 'unit_number, unit_type (truck/trailer), make, model, year, vin, status',
    exampleRows: [{
      unit_number: 'T-501',
      unit_type: 'truck',
      make: 'Freightliner',
      model: 'Cascadia',
      year: '2022',
      vin: '1FUJGHDV8NLBT9999',
      license_plate: 'TX-FLT501',
      status: 'active',
      odometer: '95000',
      trailer_type: '',
      trailer_length: '',
    }],
    mapRow: (row) => ({
      unit_number: str(row.unit_number),
      unit_type: str(row.unit_type) || 'truck',
      make: str(row.make),
      model: str(row.model),
      year: num(row.year),
      vin: str(row.vin),
      license_plate: str(row.license_plate),
      status: str(row.status) || 'active',
      odometer: num(row.odometer),
      trailer_type: str(row.trailer_type),
      trailer_length: num(row.trailer_length),
    }),
    preview: (row) => `${row.unit_number} · ${[row.make, row.model].filter(Boolean).join(' ') || row.unit_type}`,
  },
  '/portal/workorders': {
    entity: 'WorkOrder',
    label: 'Work Orders',
    headers: ['wo_number', 'title', 'repair_type', 'status', 'priority', 'vehicle_unit', 'complaint', 'labor_hours', 'labor_rate', 'parts_total', 'opened_date', 'due_date'],
    required: ['wo_number', 'title'],
    columnHint: 'wo_number, title, repair_type, status, priority, vehicle_unit (optional)',
    exampleRows: [{
      wo_number: 'WO-241001',
      title: 'Brake inspection',
      repair_type: 'Brakes',
      status: 'open',
      priority: 'high',
      vehicle_unit: 'T-101',
      complaint: 'Soft pedal reported',
      labor_hours: '2.5',
      labor_rate: '85',
      parts_total: '340',
      opened_date: '2026-07-07',
      due_date: '2026-07-10',
    }],
    mapRow: (row) => ({
      wo_number: str(row.wo_number),
      title: str(row.title),
      repair_type: str(row.repair_type) || 'Other',
      status: str(row.status) || 'open',
      priority: str(row.priority) || 'medium',
      vehicle_unit: str(row.vehicle_unit),
      complaint: str(row.complaint),
      labor_hours: num(row.labor_hours),
      labor_rate: num(row.labor_rate),
      parts_total: num(row.parts_total),
      opened_date: str(row.opened_date),
      due_date: str(row.due_date),
    }),
    preview: (row) => `${row.wo_number} · ${row.title}`,
  },
  '/portal/customers': {
    entity: 'Customer',
    label: 'Customers',
    headers: ['company_name', 'contact_name', 'email', 'phone', 'address', 'city', 'state', 'zip', 'mc_number', 'dot_number', 'fleet_size', 'status'],
    required: ['company_name'],
    columnHint: 'company_name, contact, email, phone, address, MC/DOT numbers',
    exampleRows: [{
      company_name: 'Acme Freight LLC',
      contact_name: 'John Smith',
      email: 'john@acmefreight.com',
      phone: '555-123-4567',
      address: '100 Main St',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      mc_number: 'MC-123456',
      dot_number: '1234567',
      fleet_size: '8',
      status: 'active',
    }],
    mapRow: (row) => ({
      company_name: str(row.company_name),
      contact_name: str(row.contact_name),
      email: str(row.email),
      phone: str(row.phone),
      address: str(row.address),
      city: str(row.city),
      state: str(row.state),
      zip: str(row.zip),
      mc_number: str(row.mc_number),
      dot_number: str(row.dot_number),
      fleet_size: num(row.fleet_size),
      status: str(row.status) || 'prospect',
    }),
    preview: (row) => row.company_name,
  },
  '/portal/invoices': {
    entity: 'Invoice',
    label: 'Invoices',
    headers: ['invoice_number', 'amount', 'status', 'due_date', 'description'],
    required: ['invoice_number', 'amount'],
    columnHint: 'invoice_number, amount, status, due_date, description',
    exampleRows: [{
      invoice_number: 'INV-2026-0200',
      amount: '4500',
      status: 'draft',
      due_date: '2026-08-01',
      description: 'July fleet management services',
    }],
    mapRow: (row) => ({
      invoice_number: str(row.invoice_number),
      amount: num(row.amount),
      status: str(row.status) || 'draft',
      due_date: str(row.due_date),
      description: str(row.description),
    }),
    preview: (row) => `${row.invoice_number} · $${row.amount || '0'}`,
  },
  '/portal/parts': {
    entity: 'PartInventory',
    label: 'Parts',
    headers: ['part_number', 'description', 'quantity', 'unit_cost', 'location', 'reorder_point'],
    required: ['part_number', 'description'],
    columnHint: 'part_number, description, quantity, unit_cost, location',
    exampleRows: [{
      part_number: 'BP-5500',
      description: 'Brake pad set',
      quantity: '10',
      unit_cost: '89.50',
      location: 'A-12',
      reorder_point: '4',
    }],
    mapRow: (row) => ({
      part_number: str(row.part_number),
      description: str(row.description),
      quantity: num(row.quantity) ?? 0,
      unit_cost: num(row.unit_cost),
      location: str(row.location),
      reorder_point: num(row.reorder_point),
    }),
    preview: (row) => `${row.part_number} · ${row.description}`,
  },
  '/portal/vendors': {
    entity: 'Vendor',
    label: 'Vendors',
    headers: ['name', 'type', 'phone', 'email', 'city', 'state', 'status', 'services'],
    required: ['name'],
    columnHint: 'name, type, phone, email, city, state, services',
    exampleRows: [{
      name: 'Rush Truck Centers',
      type: 'dealer',
      phone: '214-555-8800',
      email: 'service@example.com',
      city: 'Dallas',
      state: 'TX',
      status: 'active',
      services: 'Full service and parts',
    }],
    mapRow: (row) => ({
      name: str(row.name),
      type: str(row.type) || 'other',
      phone: str(row.phone),
      email: str(row.email),
      city: str(row.city),
      state: str(row.state),
      status: str(row.status) || 'active',
      services: str(row.services),
    }),
    preview: (row) => row.name,
  },
  '/portal/fuel': {
    entity: 'FuelLog',
    label: 'Fuel Logs',
    headers: ['vehicle_unit', 'gallons', 'cost', 'station_name', 'fuel_type', 'odometer', 'date'],
    required: ['gallons', 'date'],
    columnHint: 'vehicle_unit, gallons, cost, station_name, fuel_type, odometer, date',
    exampleRows: [{
      vehicle_unit: 'T-101',
      gallons: '142',
      cost: '553.58',
      station_name: 'TA Petro Dallas',
      fuel_type: 'diesel',
      odometer: '125100',
      date: '2026-07-05',
    }],
    mapRow: (row) => ({
      vehicle_unit: str(row.vehicle_unit),
      gallons: num(row.gallons),
      cost: num(row.cost),
      station_name: str(row.station_name),
      fuel_type: str(row.fuel_type) || 'diesel',
      odometer: num(row.odometer),
      date: str(row.date),
    }),
    preview: (row) => `${row.date || '?'} · ${row.gallons || '?'} gal`,
  },
  '/portal/fuel-stations': {
    entity: 'FuelStation',
    label: 'Fuel Stations',
    headers: ['name', 'brand', 'address', 'city', 'state', 'diesel_price', 'gasoline_price', 'status'],
    required: ['name', 'city', 'state'],
    columnHint: 'name, brand, address, city, state, diesel/gas prices',
    exampleRows: [{
      name: 'Pilot Travel Center #500',
      brand: 'Pilot',
      address: '1234 I-80 Exit 42',
      city: 'Omaha',
      state: 'NE',
      diesel_price: '3.899',
      gasoline_price: '3.459',
      status: 'active',
    }],
    mapRow: (row) => ({
      name: str(row.name),
      brand: str(row.brand),
      address: str(row.address),
      city: str(row.city),
      state: str(row.state),
      diesel_price: num(row.diesel_price),
      gasoline_price: num(row.gasoline_price),
      status: str(row.status) || 'active',
    }),
    preview: (row) => `${row.name} · ${row.city}, ${row.state}`,
  },
  '/portal/maintenance': {
    entity: 'MaintenanceSchedule',
    label: 'PM Schedules',
    headers: ['vehicle_unit', 'service_type', 'interval_miles', 'last_service_miles', 'next_due_miles', 'interval_months', 'last_service_date', 'next_due_date', 'status'],
    required: ['service_type'],
    columnHint: 'vehicle_unit, service_type, interval miles/months, due dates',
    exampleRows: [{
      vehicle_unit: 'T-101',
      service_type: 'PM-A',
      interval_miles: '25000',
      last_service_miles: '100000',
      next_due_miles: '125000',
      interval_months: '',
      last_service_date: '',
      next_due_date: '',
      status: 'scheduled',
    }],
    mapRow: (row) => ({
      vehicle_unit: str(row.vehicle_unit),
      service_type: str(row.service_type),
      interval_miles: num(row.interval_miles),
      last_service_miles: num(row.last_service_miles),
      next_due_miles: num(row.next_due_miles),
      interval_months: num(row.interval_months),
      last_service_date: str(row.last_service_date),
      next_due_date: str(row.next_due_date),
      status: str(row.status) || 'scheduled',
    }),
    preview: (row) => `${row.service_type} · ${row.vehicle_unit || 'fleet'}`,
  },
  '/portal/inspections': {
    entity: 'Inspection',
    label: 'Inspections',
    headers: ['vehicle_unit', 'inspection_type', 'inspection_date', 'status', 'inspector', 'notes', 'defects_found'],
    required: ['inspection_date'],
    columnHint: 'vehicle_unit, inspection_type, date, status, inspector, notes',
    exampleRows: [{
      vehicle_unit: 'T-101',
      inspection_type: 'DOT Annual',
      inspection_date: '2026-07-01',
      status: 'passed',
      inspector: 'Mike Rodriguez',
      notes: 'No defects',
      defects_found: '0',
    }],
    mapRow: (row) => ({
      vehicle_unit: str(row.vehicle_unit),
      inspection_type: str(row.inspection_type) || 'General',
      inspection_date: str(row.inspection_date),
      status: str(row.status) || 'passed',
      inspector: str(row.inspector),
      notes: str(row.notes),
      defects_found: num(row.defects_found) ?? 0,
    }),
    preview: (row) => `${row.inspection_type || 'Inspection'} · ${row.inspection_date || '?'}`,
  },
  '/portal/incidents': {
    entity: 'Incident',
    label: 'Incidents',
    headers: ['title', 'severity', 'status', 'vehicle_unit', 'date', 'description'],
    required: ['title', 'date'],
    columnHint: 'title, severity, status, vehicle_unit, date, description',
    exampleRows: [{
      title: 'Minor parking lot incident',
      severity: 'low',
      status: 'open',
      vehicle_unit: 'T-102',
      date: '2026-07-03',
      description: 'Backing contact with dock — no injuries',
    }],
    mapRow: (row) => ({
      title: str(row.title),
      severity: str(row.severity) || 'low',
      status: str(row.status) || 'open',
      vehicle_unit: str(row.vehicle_unit),
      date: str(row.date),
      description: str(row.description),
    }),
    preview: (row) => row.title,
  },
  '/portal/drivers': {
    entity: 'User',
    label: 'Drivers',
    headers: ['email', 'full_name', 'phone', 'password', 'status'],
    required: ['email', 'full_name'],
    columnHint: 'email, full_name, phone, password (optional — defaults to changeme123)',
    exampleRows: [{
      email: 'driver.new@fleetco.com',
      full_name: 'Alex Johnson',
      phone: '555-987-6543',
      password: 'changeme123',
      status: 'active',
    }],
    mapRow: (row) => ({
      email: str(row.email),
      full_name: str(row.full_name),
      phone: str(row.phone),
      password: str(row.password) || 'changeme123',
      role: 'driver',
      status: str(row.status) || 'active',
    }),
    preview: (row) => `${row.full_name} · ${row.email}`,
  },
  '/portal/hos': {
    entity: 'HOSLog',
    label: 'HOS Logs',
    headers: ['driver_name', 'status', 'hours_remaining', 'cycle_remaining', 'date'],
    required: ['driver_name', 'date'],
    columnHint: 'driver_name, status, hours_remaining, cycle_remaining, date',
    exampleRows: [{
      driver_name: 'Mike Rodriguez',
      status: 'driving',
      hours_remaining: '6.5',
      cycle_remaining: '42',
      date: '2026-07-07',
    }],
    mapRow: (row) => ({
      driver_name: str(row.driver_name),
      status: str(row.status) || 'off_duty',
      hours_remaining: num(row.hours_remaining),
      cycle_remaining: num(row.cycle_remaining),
      date: str(row.date),
    }),
    preview: (row) => `${row.driver_name} · ${row.date}`,
  },
  '/portal/service-templates': {
    entity: 'ServiceTemplate',
    label: 'Service Templates',
    headers: ['name', 'service_type', 'description', 'estimated_hours', 'estimated_cost'],
    required: ['name', 'service_type'],
    columnHint: 'name, service_type, description, estimated hours/cost',
    exampleRows: [{
      name: 'PM-A Service',
      service_type: 'Preventive Maintenance',
      description: 'Standard PM-A interval service',
      estimated_hours: '4',
      estimated_cost: '485',
    }],
    mapRow: (row) => ({
      name: str(row.name),
      service_type: str(row.service_type),
      description: str(row.description),
      estimated_hours: num(row.estimated_hours),
      estimated_cost: num(row.estimated_cost),
    }),
    preview: (row) => row.name,
  },
  '/portal/messages': {
    entity: 'Message',
    label: 'Messages',
    headers: ['subject', 'body', 'from_user', 'to_role'],
    required: ['subject', 'body'],
    columnHint: 'subject, body, from_user, to_role (all/driver/etc.)',
    exampleRows: [{
      subject: 'Weekly safety reminder',
      body: 'Complete pre-trip inspections before departure.',
      from_user: 'Fleet Manager',
      to_role: 'driver',
    }],
    mapRow: (row) => ({
      subject: str(row.subject),
      body: str(row.body),
      from_user: str(row.from_user) || 'FleetCo Admin',
      to_role: str(row.to_role) || 'all',
      read: false,
    }),
    preview: (row) => row.subject,
  },
  '/portal/domain-emails': {
    entity: 'DomainEmail',
    label: 'Domain Emails',
    headers: ['email', 'display_name', 'role', 'status'],
    required: ['email'],
    columnHint: 'email, display_name, role, status',
    exampleRows: [{
      email: 'dispatch@fleetcomanagement.org',
      display_name: 'Dispatch',
      role: 'fleet_coordinator',
      status: 'active',
    }],
    mapRow: (row) => ({
      email: str(row.email),
      display_name: str(row.display_name),
      role: str(row.role),
      status: str(row.status) || 'active',
    }),
    preview: (row) => row.email,
  },
};

export function getBulkImportConfig(pathname) {
  return BULK_IMPORT_BY_ROUTE[pathname] || null;
}

export function validateBulkRows(config, rows) {
  const errors = [];
  const mapped = rows.map((row, i) => {
    for (const field of config.required) {
      if (!String(row[field] ?? '').trim()) {
        errors.push(`Row ${row._row || i + 2}: "${field}" is required.`);
      }
    }
    try {
      return config.mapRow(row);
    } catch (err) {
      errors.push(`Row ${row._row || i + 2}: ${err.message}`);
      return null;
    }
  });
  if (errors.length) throw new Error(errors.slice(0, 5).join('\n') + (errors.length > 5 ? `\n…+${errors.length - 5} more` : ''));
  return mapped;
}
