import { jsPDF } from 'jspdf';
import { equipmentLabel } from '@/lib/equipmentTypes';

export function buildRateConfirmationPdfBase64(load, broker = {}) {
  const doc = new jsPDF();
  const margin = 14;
  let y = 18;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('RATE CONFIRMATION', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const rows = [
    ['Load #', load.load_number || '—'],
    ['Broker / Shipper', broker.name || load.broker || '—'],
    ['Origin', load.origin || `${load.origin_city || ''}, ${load.origin_state || ''}`.trim()],
    ['Destination', load.destination || `${load.destination_city || ''}, ${load.destination_state || ''}`.trim()],
    ['Pickup', load.pickup_date || '—'],
    ['Delivery', load.delivery_date || '—'],
    ['Rate', load.rate != null ? `$${Number(load.rate).toLocaleString()}` : '—'],
    ['Miles', load.miles != null ? String(load.miles) : '—'],
    ['Weight', load.weight || '—'],
    ['Commodity', load.commodity || '—'],
    ['Equipment', load.required_equipment_type ? equipmentLabel(load.required_equipment_type) : '—'],
  ];

  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value).slice(0, 80), margin + 42, y);
    y += 6;
  });

  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Special instructions', margin, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  const notes = load.notes || 'None';
  doc.text(doc.splitTextToSize(notes, 180), margin, y);

  y += 20;
  doc.setFontSize(8);
  doc.text('Generated by FleetCo Management — not a substitute for signed carrier agreement.', margin, 280);

  return doc.output('datauristring').split(',')[1];
}

export function downloadRateConfirmationPdf(load, broker) {
  const base64 = buildRateConfirmationPdfBase64(load, broker);
  const blob = new Blob([Uint8Array.from(atob(base64), (c) => c.charCodeAt(0))], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `RateCon-${load.load_number || 'load'}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
